name: 'Setup Ghidra Action'
author: 'antoniovazquezblanco'
description: 'Setup Ghidra environment'

inputs:
  download_url:
    description: 'Direct download url to a Ghidra distribution archive.'
  owner:
    description: 'Owner of the repository to fetch Ghidra from.'
    default: 'NationalSecurityAgency'
  repo:
    description: 'Repository to fetch Ghidra from.'
    default: 'ghidra'
  version:
    description: 'Ghidra version.'
    default: 'latest'
  auth_token:
    description: 'GitHub token for authentication.'
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'code'
  color: 'yellow'
